In [3]:
import pandas as pd
import os

In [ ]:
data2 = pd.read_csv("final_hateXplain.csv")
data2.head()

,comment,label,Race,Religion,Gender,Sexual Orientation,Miscellaneous
0,0 u0 lmao wow fuck you too 😂 😂,normal,No_race,Nonreligious,No_gender,No_orientation,NaN
1,1 0 th floor maybe wow cnn with the fakenews t...,offensive,No_race,Nonreligious,No_gender,No_orientation,Other
2,1 0 yrs <number> white women raped by niggers ...,hatespeech,African,Nonreligious,No_gender,No_orientation,NaN
3,1 2 h ago ching chong accepted your friend req...,offensive,Asian,Nonreligious,No_gender,No_orientation,NaN
4,1 8 th century mayhem and lawlessness had noth...,normal,No_race,Nonreligious,No_gender,No_orientation,NaN

In [42]:
data.head()
data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 39252 entries, 6 to 60443
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   post_id       39252 non-null  object
 1   annotator_id  39252 non-null  int64
 2   label         39252 non-null  object
 3   target        39252 non-null  object
 4   post_tokens   39252 non-null  object
dtypes: int64(1), object(4)
memory usage: 1.8+ MB

       annotator_id
count  39252.000000
mean     134.882503
std       94.603133
min        1.000000
25%       18.000000
50%      202.000000
75%      212.000000
max      253.000000

In [ ]:
data2.isnull().sum()

comment                   0
label                     0
Race                      0
Religion                  0
Gender                    0
Sexual Orientation        0
Miscellaneous         16576
dtype: int64

In [44]:
import re
data2["comment"] = data2["comment"].str.replace(r"<[^>]+>", "", regex=True)
# remove <> 
data2.head()

,comment,label,Race,Religion,Gender,Sexual Orientation,Miscellaneous
0,0 u0 lmao wow fuck you too,normal,No_race,Nonreligious,No_gender,No_orientation,NaN
1,1 0 th floor maybe wow cnn with the fakenews t...,offensive,No_race,Nonreligious,No_gender,No_orientation,Other
2,1 0 yrs white women raped by niggers negress...,hatespeech,African,Nonreligious,No_gender,No_orientation,NaN
3,1 2 h ago ching chong accepted your friend req...,offensive,Asian,Nonreligious,No_gender,No_orientation,NaN
4,1 8 th century mayhem and lawlessness had noth...,normal,No_race,Nonreligious,No_gender,No_orientation,NaN

In [ ]:
data2["comment"] = data2["comment"].str.replace(r"http\S+|www\S+", "", regex=True)
data2.head()
# remove url

,comment,label,Race,Religion,Gender,Sexual Orientation,Miscellaneous
0,0 u0 lmao wow fuck you too,normal,No_race,Nonreligious,No_gender,No_orientation,NaN
1,1 0 th floor maybe wow cnn with the fakenews t...,offensive,No_race,Nonreligious,No_gender,No_orientation,Other
2,1 0 yrs white women raped by niggers negress...,hatespeech,African,Nonreligious,No_gender,No_orientation,NaN
3,1 2 h ago ching chong accepted your friend req...,offensive,Asian,Nonreligious,No_gender,No_orientation,NaN
4,1 8 th century mayhem and lawlessness had noth...,normal,No_race,Nonreligious,No_gender,No_orientation,NaN

In [ ]:
data2["comment"] = data2["comment"].str.replace(r"[^\x00-\x7F]+", "", regex=True)
data2.head()
# remove emoji

,comment,label,Race,Religion,Gender,Sexual Orientation,Miscellaneous
0,0 u0 lmao wow fuck you too,normal,No_race,Nonreligious,No_gender,No_orientation,NaN
1,1 0 th floor maybe wow cnn with the fakenews t...,offensive,No_race,Nonreligious,No_gender,No_orientation,Other
2,1 0 yrs white women raped by niggers negress...,hatespeech,African,Nonreligious,No_gender,No_orientation,NaN
3,1 2 h ago ching chong accepted your friend req...,offensive,Asian,Nonreligious,No_gender,No_orientation,NaN
4,1 8 th century mayhem and lawlessness had noth...,normal,No_race,Nonreligious,No_gender,No_orientation,NaN

## Tweet Target Analysis
Count how many tweets are targeted towards each category (Race, Religion, Gender, Sexual Orientation, Miscellaneous)

In [1]:
# Count tweets targeted towards each category
# A tweet is "targeted" if it has a specific group (not the default "no target" value)

race_targeted = (data2["Race"] != "No_race").sum()
religion_targeted = (data2["Religion"] != "Nonreligious").sum()
gender_targeted = (data2["Gender"] != "No_gender").sum()
orientation_targeted = (data2["Sexual Orientation"] != "No_orientation").sum()
misc_targeted = data2["Miscellaneous"].notna().sum()

target_summary = pd.DataFrame({
    "Category": ["Race", "Religion", "Gender", "Sexual Orientation", "Miscellaneous"],
    "Tweet Count": [race_targeted, religion_targeted, gender_targeted, orientation_targeted, misc_targeted]
})
target_summary["Percentage (%)"] = (target_summary["Tweet Count"] / len(data2) * 100).round(2)

print(f"Total tweets: {len(data2)}\n")
print(target_summary.to_string(index=False))

NameError: name 'data2' is not defined

In [ ]:
# Breakdown of specific groups within each category
print("=== Race Breakdown ===")
print(data2[data2["Race"] != "No_race"]["Race"].value_counts().to_string())

print("\n=== Religion Breakdown ===")
print(data2[data2["Religion"] != "Nonreligious"]["Religion"].value_counts().to_string())

print("\n=== Gender Breakdown ===")
print(data2[data2["Gender"] != "No_gender"]["Gender"].value_counts().to_string())

print("\n=== Sexual Orientation Breakdown ===")
print(data2[data2["Sexual Orientation"] != "No_orientation"]["Sexual Orientation"].value_counts().to_string())

print("\n=== Miscellaneous Breakdown ===")
print(data2[data2["Miscellaneous"].notna()]["Miscellaneous"].value_counts().to_string())